#ifndef MCU_CONFIG_H_
#define MCU_CONFIG_H_

#include "secrets.h"

#define DEBUG_ENABLED
#define DEBUG_SERIAL Serial

#define POWER_RELAY_PIN    14

#define DISPLAY_CLK_PIN    5
#define DISPLAY_DATA_PIN   19
#define DISPLAY_LATCH_PIN  18

#define DISPLAY_ZONE_COUNT 12
#define DISPLAY_ROWS_COUNT 8
#define DISPLAY_COLS_COUNT (DISPLAY_ZONE_COUNT * 8)

#define WIFI_SSID "BKSPIOT"
#define WIFI_PASSWORD (SECRET_WIFI_PASSWORD)

#define MQTT_HOST "mqtt.svc.bksp.in"
#define MQTT_PORT 8883
#define MQTT_CA_CERTIFICATE "-----BEGIN CERTIFICATE-----\n" \
"MIICJDCCAamgAwIBAgIIey8Vp8RZsH0wCgYIKoZIzj0EAwMwPTELMAkGA1UEBhMC\n" \
"UlUxEjAQBgNVBAoTCUI0Q0tTUDRDRTEaMBgGA1UEAxMRQjRDS1NQNENFIFJvb3Qg\n" \
"Q0EwHhcNMjQxMTE1MDAwMDAwWhcNNDkxMTE0MjM1OTU5WjA9MQswCQYDVQQGEwJS\n" \
"VTESMBAGA1UEChMJQjRDS1NQNENFMRowGAYDVQQDExFCNENLU1A0Q0UgUm9vdCBD\n" \
"QTB2MBAGByqGSM49AgEGBSuBBAAiA2IABM4CKl0DiWe1Ys8U4uqlZMOLLWqLI9V+\n" \
"CUiDpu5FG3MTxrAAcPfZuQ/kCzjd54DNMUF8zVAVzMaHeqV0/53s8xXFuQF5l2x6\n" \
"813yeH5AtceIX8ht3QCe+IhsTRSAug1rTKN2MHQwDwYDVR0TAQH/BAUwAwEB/zAd\n" \
"BgNVHQ4EFgQUzj1SwIlPV2Leax2jx0yt51YTWOUwDgYDVR0PAQH/BAQDAgGGMDIG\n" \
"A1UdHwQrMCkwJ6AloCOGIWh0dHA6Ly9jYS5ia3NwLmluL3Jvb3QvcmV2b2tlLmNy\n" \
"bDAKBggqhkjOPQQDAwNpADBmAjEAwGFmYbxsnCdzRXyHwgp9pyMRFoMjCx0EDB6q\n" \
"tL3G1QIx1UNuzsIPNYI9yKo9EE8UAjEA2hcR/KYp3xQj1zXiqIE0LsqkGk0hut0e\n" \
"RiO4bCkrxeZkLzX5JC84EHK6AC8c4AzQ\n" \
"-----END CERTIFICATE-----\n"
#define MQTT_USERNAME "openspace-signage"
#define MQTT_PASSWORD (SECRET_MQTT_PASSWORD)
#define MQTT_BASE_TOPIC "bus/devices/openspace-signage"

#endif //MCU_CONFIG_H_